version: "3.9"

services:
  twilio-monitor:
    container_name: twilio-monitor
    build:
      context: .
      dockerfile: containers/twilio-monitor/Dockerfile
    volumes:
      - .:/code
    tty: true
    env_file:
      - .env.dev
    networks:
      - shared_network

networks:
  shared_network:
    external: true